import Head from "next/head";
import { Inter } from "next/font/google";
import { Onepage } from "./onepage";
import { Navbar } from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-900" >
      <div className=" sticky top-0 z-50 bg-slate-900">
        <Navbar />
        </div>
        <Onepage />
      </main>
    </>
  );
}
