import Head from "next/head";
import React from 'react';
import { Inter } from "next/font/google";
import  Mailer  from "./mailer";
import Histories  from "./histories";
import Banner from "./banner";
import Footer from "./footer";
import Skill from "./skill";
import Mydescribe from "./mydescribe";
import Slideshow from "./slideshow";
import Navbar from "./navbar";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-900" >
      <div className=" sticky top-0 z-50 bg-slate-900">
        <Navbar />
        </div>
        <section className="text-white p-10">

{/* baner */}
<Banner />
</section>
<Mydescribe />

<section  id="skill" className="pt-16 bg-white  " > 
<Skill />
{/* History */}
<span id="aboutme" className=" pt-20">
<Histories />
</span>
<div className="bg-white p-10 pt-20" id="portofolio">
  <p className="font-bold text-2xl">Portofolio</p>
  <Slideshow />
</div>
</section>
<span id="contactme" >
<Mailer />
</span>
<Footer />
      </main>
    </>
  );
}
